name: Collaborative Workflow

on:
 push: 
  branches: 
   -main

jobs:
  update_html_and_readme:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
      sed -i '/<\/body>/i <p>Updated by Team Leader on "'$(date)'"</p>' index.html
      sed -i '/<\/body>/i <p>Updated by Member 1 on "'$(date)'"</p>' index.html

